locals {
  self_env = coalesce(
    var.self_state_environment,
    contains(keys(var.environments), "prod") ? "prod" : sort(keys(var.environments))[0],
  )

  # Rendered backend configuration, one per environment. Generated rather than
  # hand-copied so the bucket name and APPID can never drift out of sync.
  backend_hcl = {
    for env, name in local.bucket_names : env => <<-HCL
      # Generated by bootstrap/. Do not edit by hand.
      #   terraform init -backend-config=backend.hcl
      bucket = "${name}"
      region = "${var.region}"
      prefix = "${local.state_prefixes[env]}"
      key    = "terraform.tfstate"

      encrypt = true
      acl     = "private"
    HCL
  }
}

output "state_bucket_names" {
  description = "State bucket name per environment."
  value       = local.bucket_names
}

output "state_bucket_urls" {
  description = "COS endpoint per environment."
  value       = { for env, b in tencentcloud_cos_bucket.state : env => b.cos_bucket_url }
}

output "app_id" {
  description = "Account APPID the bucket names are suffixed with."
  value       = local.app_id
}

output "backend_hcl" {
  description = <<-EOT
    Ready-to-write backend config per environment. With write_backend_files
    enabled (the default) these are already on disk in envs/*/backend.hcl.

    To emit one by hand instead -- note that `terraform output -raw` takes an
    output name, not an index expression, so this has to go through JSON:

      terraform output -json backend_hcl | jq -r '.staging' > ../envs/staging/backend.hcl
  EOT
  value       = local.backend_hcl
}

output "self_backend_hcl" {
  description = <<-EOT
    Backend config for this bootstrap root itself, so it stops depending on a
    local state file:

      terraform output -raw self_backend_hcl > backend.hcl
      terraform init -backend-config=backend.hcl -migrate-state
  EOT
  value       = <<-HCL
    # Generated by bootstrap/. Do not edit by hand.
    bucket = "${local.bucket_names[local.self_env]}"
    region = "${var.region}"
    prefix = "bootstrap"
    key    = "terraform.tfstate"

    encrypt = true
    acl     = "private"
  HCL
}

output "cam_policy_names" {
  description = "Least-privilege state-access policy per environment. Attach these to CI roles."
  value       = { for env, p in tencentcloud_cam_policy.state_access : env => p.name }
}
