# Generated by bootstrap/. Do not edit by hand.
#   terraform init -backend-config=backend.hcl
#
# The APPID suffix below is a placeholder until `bootstrap` has been applied
# against the client's account; it rewrites this file with the real value.
bucket = "acme-tfstate-prod-1250000000"
region = "ap-singapore"
prefix = "platform/prod"
key    = "terraform.tfstate"

encrypt = true
acl     = "private"
