# Generated by stacks/bootstrap. Do not edit by hand.
#   terraform init -backend-config=backend.hcl
#
# APPID suffix is a placeholder until `make bootstrap CLIENT=training` has run
# against the account; it rewrites this file with the real value.
bucket = "training-tfstate-staging-1250000000"
region = "ap-singapore"
prefix = "platform/staging"
key    = "terraform.tfstate"

encrypt = true
acl     = "private"
