# Generated by bootstrap/. Do not edit by hand.
bucket = "training-tfstate-staging-1473945127"
region = "ap-singapore"
prefix = "bootstrap"
key    = "terraform.tfstate"

encrypt = true
acl     = "private"
